# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Do6NIIN4cgJvsJ24hyGb5XP7ZTJdRV0Y
"""

import pandas as pd
import math

df = pd.read_excel("/content/drive/MyDrive/cranfield_q1_dataset.xlsx")

df_q1 = df[df["Query ID"] == "q1"].sort_values("Rank")

retrived = df_q1["Document ID"].tolist()
relevant = set(df_q1[df_q1["Is_Relevant"] == "Yes"]["Document ID"].tolist())

def precision(retrived, relevant):
    if not retrived:
        return 0

    count = 0
    for doc in retrived:
        if doc in relevant:
            count += 1

    return count / len(retrived)

def recall(retrived , relevant):
  if not relevant:
    return 0

  count = 0
  for doc in retrived:
    if doc in relevant:
      count+=1

  return count / len(relevant)

def f_measure(p,r):
  if (p+r) == 0 : return 0
  return 2*p*r / ( p + r)

def e_measure(p, r, beta=1):
    if p == 0 and r == 0: return 1
    return 1 - ((1 + beta**2) * p * r) / (beta**2 * p + r)

def dcg(retrived, relevant):
    dcg_value = 0.0
    for i, doc in enumerate(retrived):
        if doc in relevant:
            dcg_value += 1 / math.log2(i + 2)
    return dcg_value

def idcg(relevant, k):
    idcg_value = 0.0
    max_items = min(len(relevant), k)

    for i in range(max_items):
        idcg_value += 1 / math.log2(i + 2)

    return idcg_value

def ndcg(retrived, relevant):
    dcg_val = dcg(retrived, relevant)
    idcg_val = idcg(relevant, len(retrived))
    return dcg_val / idcg_val if idcg_val > 0 else 0

p = precision(retrived, relevant)
r = recall(retrived, relevant)
f = f_measure(p, r)
e = e_measure(p, r)
n = ndcg(retrived, relevant)

print("Precision:", round(p, 3))
print("Recall:", round(r, 3))
print("F-measure:", round(f, 3))
print("E-measure:", round(e, 3))
print("NDCG:", round(n, 3))